<?php

$debug[IP] = $_SERVER[HTTP_X_FORWARDED_FOR] ?? $_SERVER[SERVER_ADDR];

if (empty($debug[IP])) {
    
    $debug[IP] = $_SERVER[REMOTE_ADDR];
    $debug[PORT] = $_SERVER[REMOTE_PORT];

} else {
    
    $debug[PORT] = $_SERVER[HTTP_X_FORWARDED_PORT];
    $debug[PROTOCOL] = $_SERVER[HTTP_X_FORWARDED_PROTO];

}

$_SERVER[SERVER_NAME];
$_SERVER[SERVER_PORT];
$_SERVER[SERVER_PROTOCOL];
$_SERVER[SERVER_SOFTWARE];

$_SERVER[USER];
$_SERVER[PORT];
 